### ISSUE TITLE
Crash with NeoForge

### ISSUE THREAD

**Issue by MasterGeneral156** [MasterGeneral156/MoGlowstone-Mod#10]
Taken from https://www.curseforge.com/minecraft/mc-mods/mo-glowstone/comments: audioforcestv

A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

 

-- Head --

Thread: main

Stacktrace:

        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.23.jar%2360!/:4.0] {}

-- MOD moglowstone --

Details:

        Mod File: /K:/games/neo dedicated/mods/mo-glowstone-neo-1.21-2.6.2.jar

        Failure message: fml.modloadingissue.errorduringevent

        Failure message arg 1: net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent

        Mod Version: 2.6.2

        Mod Issue URL: https://github.com/MasterGeneral156/MoGlowstone-Mod/issues

        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER

Stacktrace:

        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.common.asm.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:60) ~[loader-4.0.23.jar%2360!/:4.0] {}

        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar%2362!/:?] {}

        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar%2362!/:?] {}

        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar%2362!/:?] {}

        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?] {}

        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}

        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) ~[securejarhandler-3.0.8.jar:?] {}

        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?] {}

        at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) ~[securejarhandler-3.0.8.jar:?] {}

        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}

        at TRANSFORMER/moglowstone@2.6.2/com.themastergeneral.moglowstone.MoGlowstone.setup(MoGlowstone.java:62) ~[mo-glowstone-neo-1.21-2.6.2.jar%23226!/:?] {re:classloading}

        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.1.jar%2367!/:?] {}

        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%2367!/:?] {}

        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%2367!/:?] {}

        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:158) ~[loader-4.0.23.jar%2360!/:4.0] {re:mixin}

        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.lambda$dispatchParallelEvent$4(ModLoader.java:172) ~[loader-4.0.23.jar%2360!/:4.0] {}

        at MC-BOOTSTRAP/fml_loader@4.0.23/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.23.jar%2360!/:4.0] {}

        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {re:mixin}

        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}

        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}

        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}

        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}

        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}

        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}

        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}`

**Comment by EpicKeyboardGuy** [comment]
Found the fix ! I wrote to MasterGeneral156 but just in case he never sees my message, here it is :

![MoGlowstone java - SERVER FIX NeoForge](https://github.com/user-attachments/assets/3cc9b916-6166-4ff2-8b70-587913fea593)

**Comment by MasterGeneral156** [comment]
This just popped in my email. Man I'm a slow fart sometimes lol. I'll get this commited and builds updated within the next day. Got tomorrow off work, so definitely guaranteed by then.Thank you again ❤️Sent from Android device

**Comment by MasterGeneral156** [comment]
[v2.6.3b](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone/files/5988225) for 1.21.1 and [v2.6.2b](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone/files/5988271) for 1.21
Hoping this helps guys! This also made me realize the active codebase has this issue too lmao. I'll leave this open for a few days to have y'all confirm or not this has been squished. If I don't hear back from y'all, have happy holidays and thank you so much for using Mo' Glowstone <3
